### ISSUE TITLE
cancel order

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/circuits#40]

**Comment by lispc** [comment]
<https://github.com/Fluidex/circuits/issues/38> and this may be handled in the offchain matchengine ( at least in short term )

**Comment by HAOYUatHZ** [comment]
> #38 and this may be handled in the offchain matchengine ( at least in short term ) ?

emmm I see.   kinda like batch trades?

**Comment by HAOYUatHZ** [comment]
In the future, we still need `cancel_order`.

Because before we insert into order leaf, we need `place_order` and need to verify `place_order` signature in the circuit -- the server should not just modify the circuit by itself.

And once we have  `place_order`, we then probably need  `cancel_order`

**Comment by HAOYUatHZ** [comment]
Another alternative solution is 

do not have cancel_order & place_order anymore,
and 
verify signature in spot_trade circuit.

This is a trade-off.
