### ISSUE TITLE
feature: add signature validation in PlaceOrder

### ISSUE THREAD

**Issue by lispc** [Fluidex/circuits#95]

**Comment by HAOYUatHZ** [comment]
We would like to add signature verification in https://github.com/Fluidex/circuits/blob/master/src/place_order.circom like in 

+ https://github.com/Fluidex/circuits/blob/af124e57ca6f4c259999b83a18884e24124addb3/src/withdraw.circom#L77-L95
+ https://github.com/Fluidex/circuits/blob/af124e57ca6f4c259999b83a18884e24124addb3/src/transfer.circom#L170-L188


First, try to add this feature to https://github.com/Fluidex/circuits/blob/master/src/place_order.circom.

Then, try to upgrade https://github.com/Fluidex/circuits/blob/master/tpl/ejs/src/place_order.circom.ejs to generate the new  https://github.com/Fluidex/circuits/blob/master/src/place_order.circom.

Third, upgrade the corresponding test https://github.com/Fluidex/circuits/blob/master/test/place_order.ts like in 
+ https://github.com/Fluidex/circuits/blob/af124e57ca6f4c259999b83a18884e24124addb3/test/withdraw.ts#L41-L49
+ https://github.com/Fluidex/circuits/blob/af124e57ca6f4c259999b83a18884e24124addb3/test/transfer.ts#L59-L69
